INSERT INTO PARK (ID,JAUGE_MAX,NB_MAX_JOURNALIER) VALUES (1,1000,0);

-- 0 = employee, 1 = admin, 2 = manager
INSERT INTO EMPLOYEE (ID,FIRST_NAME,NAME,EMAIL,ROLE) VALUES (1,'Tchouk','Tchouk','tchoukdu12@gmail.com','2');
INSERT INTO EMPLOYEE (ID,FIRST_NAME,NAME,EMAIL,ROLE) VALUES (2,'Adam','Khalepo','adam@gmail.com','0');
INSERT INTO EMPLOYEE (ID,FIRST_NAME,NAME,EMAIL,ROLE) VALUES (3,'Lydia','Boulfrad','lydia@gmail.com','0');
INSERT INTO EMPLOYEE (ID,FIRST_NAME,NAME,EMAIL,ROLE) VALUES (4,'Maneva','Rasolondraibe','maneva@gmail.com','1');

INSERT INTO VISITOR (ID,FIRST_NAME,NAME,EMAIL) VALUES (1,'Rémi','Saurel','remi@gmail.com');
INSERT INTO VISITOR (ID,FIRST_NAME,NAME,EMAIL) VALUES (2,'Chaimae','Khama','chaimae@gmail.com');

INSERT INTO TICKET (ID,VISIT_DATE,VISITOR_ID,PRICE,STATE) VALUES (1,'2023-05-25',1,30,0);
INSERT INTO TICKET (ID,VISIT_DATE,VISITOR_ID,PRICE,STATE) VALUES (2,'2023-05-25',1,30,1);
INSERT INTO TICKET (ID,VISIT_DATE,VISITOR_ID,PRICE,STATE) VALUES (3,'2023-05-25',1,30,2);